# languages.py

LANGUAGES = {
    'fa': {
        'name': 'فارسی',
        'select_style': '📊 **سبک معاملاتی خود را انتخاب کنید:**',
        'select_mode': '🌀 **حالت معاملاتی Surpri3e Strategy را انتخاب کنید:**',
        'select_timeframe': '⏱️ **تایم‌فریم را انتخاب کنید:**',
        'select_rr': '🎯 **نسبت ریسک به ریوارد (RR) را انتخاب کنید:**',
        'change_lang': '🌍 تغییر زبان',
        'tf_1min': '1 دقیقه',
        'tf_5min': '5 دقیقه',
        'tf_15min': '15 دقیقه',
        'tf_1h': '1 ساعت',
        'tf_4h': '4 ساعت',
        'tf_1d': '1 روز',
        'signal_btn': '🚨 دریافت سیگنال',
        'performance_btn': '📊 عملکرد',
        'history_btn': '📜 تاریخچه',
        'price_btn': '💰 قیمت لحظه‌ای',
        'vip_btn': '💎 VIP',
        'referral_btn': '👥 رفرال',
        'settings_btn': '⚙️ تنظیمات',
        'support_btn': '🆘 پشتیبانی',
        'back_btn': '🔙 برگشت',
        'copy_link': '📤 کپی لینک',
        'tp_btn': '✅ TP HIT',
        'sl_btn': '❌ SL HIT',
        'cancel_btn': '🚫 CANCEL',
        'signal_title': 'سیگنال جدید',
        'style_label': 'سبک',
        'direction_label': 'جهت',
        'entry_label': 'ورود',
        'sl_label': 'حد ضرر',
        'tp_label': 'حد سود',
        'rr_label': 'نسبت RR',
        'reasons_label': 'دلایل',
        'timeframe_label': 'تایم‌فریم',
        'price_label': 'قیمت لحظه‌ای',
        'time_label': 'زمان تهران',
        'result_label': 'نتیجه معامله را انتخاب کنید',
        'tp_registered': '✅ **TP ثبت شد**\n\nبرای ادامه از دکمه‌های زیر استفاده کنید:',
        'sl_registered': '❌ **SL ثبت شد**\n\nبرای ادامه از دکمه‌های زیر استفاده کنید:',
        'canceled': '🚫 **سیگنال لغو شد**\n\nبرای ادامه از دکمه‌های زیر استفاده کنید:',
        'no_signal': '❌ **سیگنالی پیدا نشد**',
        'error': 'خطا',
        'welcome_back': '🤖 **به پنل خوش آمدید**',
        'fetching_price': '💰 **در حال دریافت قیمت...**',
        'price_result': '💰 **قیمت لحظه‌ای طلا**\n\n📊 XAU/USD\n\n💵 قیمت: {price:.2f} USD\n🕐 زمان تهران: {time}',
        'price_error': '❌ **خطا در دریافت قیمت**\n\nلطفاً دوباره تلاش کنید.',
        'signal_disabled': '⛔ **سیگنال‌دهی غیرفعال است.**',
        'no_signals_left': '❌ **تعداد سیگنال روزانه شما تمام شده!**\nصبر کنید تا فردا یا از طریق رفرال افزایش دهید.',
        'signal_cooldown': '⏱️ **کمی زود است!**\nبرای تایم‌فریم {timeframe} باید {wait} دیگر صبر کنید تا کندل جدید ببندد.',
        'market_closed': '🌙 **بازار طلا (XAU/USD) هم‌اکنون بسته است.**\n\nبازار فارکس/طلا از جمعه شب تا یکشنبه شب (به وقت جهانی) تعطیل است. لطفاً پس از بازگشایی بازار دوباره تلاش کنید.',
        'loading_frame_1': '🔍 در حال بررسی ساختار بازار.',
        'loading_frame_2': '🔍 در حال بررسی ساختار بازار..',
        'loading_frame_3': '📊 در حال تحلیل نقاط چرخش و نواحی نقدینگی...',
        'loading_frame_4': '🧠 در حال جمع‌بندی نهایی سیگنال....',
        'analyzing': '🔍 **در حال تحلیل ({timeframe})...**',
        'use_buttons': '❌ **لطفاً از دکمه‌ها استفاده کنید!**',
        'performance_text': '📊 **آمار عملکرد شما**\n\n🗓️ **این هفته:** {weekly_wins} برد از {weekly_total} معامله ({weekly_winrate}%)\n📅 **این ماه:** {monthly_wins} برد از {monthly_total} معامله ({monthly_winrate}%)\n\n📈 **کل معاملات بسته‌شده:** {total}\n✅ **برنده:** {wins}\n❌ **بازنده:** {losses}\n🎯 **نرخ موفقیت کلی:** {winrate}%\n\n📊 **سیگنال باقی‌مانده امروز:** {left}',
        'performance_menu_text': '📊 **بخش عملکرد**\n\nبرای مشاهده‌ی آمار وین‌ریت خودتان (بر اساس معاملاتی که خودتان TP یا SL را ثبت کرده‌اید)، یکی از بازه‌های زیر را انتخاب کنید:\n\n📊 **سیگنال باقی‌مانده امروز:** {left}',
        'weekly_btn': '🗓️ عملکرد هفتگی',
        'monthly_btn': '📅 عملکرد ماهانه',
        'weekly_performance_text': '🗓️ **عملکرد هفتگی شما**\n\n📈 **کل معاملات بسته‌شده:** {total}\n✅ **برنده (TP):** {wins}\n❌ **بازنده (SL):** {losses}\n🎯 **نرخ موفقیت:** {winrate}%\n\n_بر اساس معاملاتی که خودتان طی ۷ روز اخیر TP یا SL را ثبت کرده‌اید._',
        'monthly_performance_text': '📅 **عملکرد ماهانه شما**\n\n📈 **کل معاملات بسته‌شده:** {total}\n✅ **برنده (TP):** {wins}\n❌ **بازنده (SL):** {losses}\n🎯 **نرخ موفقیت:** {winrate}%\n\n_بر اساس معاملاتی که خودتان طی ۳۰ روز اخیر TP یا SL را ثبت کرده‌اید._',
        'history_title': '📜 **تاریخچه معاملات:**',
        'no_history': '📭 **هنوز معامله‌ای ندارید!**',
        'vip_intro_text': '💎 **عضویت VIP Surpri3e**\n\nدسترسی به همه‌ی پلن‌ها و سیگنال نامحدود — بدون سقف روزانه، بدون صف انتظار.\n\n⚡ سیگنال نامحدود در تمام تایم‌فریم‌ها\n🌀 اولویت در تحلیل و اجرای استراتژی Surpri3e\n📊 دسترسی کامل به آمار و گزارش عملکرد اختصاصی\n🎯 امکان تنظیم RR اختصاصی روی هر معامله\n🆘 پشتیبانی اختصاصی و پاسخ‌گویی سریع‌تر\n\nیکی از پلن‌های زیر را انتخاب کنید:',
        'vip_plan_btn_1m': '🥉 ۱ ماهه — ۵۰۰,۰۰۰ تومان',
        'vip_plan_btn_3m': '🥈 ۳ ماهه — ۱,۴۰۰,۰۰۰ تومان',
        'vip_plan_btn_6m': '🥇 ۶ ماهه — ۲,۹۰۰,۰۰۰ تومان',
        'vip_plan_btn_12m': '💎 ۱۲ ماهه — ۴,۸۰۰,۰۰۰ تومان',
        'vip_payment_card_text': '💳 **پرداخت پلن {plan}**\n\nمبلغ قابل پرداخت: **{price:,} تومان**\n\nلطفاً مبلغ را به شماره کارت زیر واریز کنید:\n`{card_number}`\n{card_holder_line}\n\nپس از واریز، روی دکمه‌ی زیر بزنید تا مراحل تکمیل شود.',
        'vip_card_not_set': '⚠️ شماره کارت هنوز از پنل مدیریت تنظیم نشده است. لطفاً بعداً دوباره تلاش کنید یا با پشتیبانی در تماس باشید.',
        'vip_paid_btn': '✅ پرداخت کردم',
        'vip_ask_phone': '📞 **شماره تماس**\n\nلطفاً شماره تماس خود را برای پیگیری پرداخت ارسال کنید (مثال: `09121234567`):',
        'vip_invalid_phone': '❌ شماره تماس نامعتبر است. لطفاً یک شماره معتبر ارسال کنید (مثال: `09121234567`).',
        'vip_ask_receipt': '🧾 **عکس رسید پرداخت**\n\nلطفاً عکس رسید واریزی خود را همینجا ارسال کنید:',
        'vip_receipt_not_photo': '❌ لطفاً رسید را به‌صورت **عکس** ارسال کنید، نه فایل یا متن.',
        'vip_request_submitted': '✅ **درخواست شما ثبت شد!**\n\nرسید و اطلاعات شما برای بررسی برای ادمین ارسال شد. پس از تایید، اشتراک VIP شما فعال خواهد شد و به شما اطلاع داده می‌شود.\n\n⏳ معمولاً این بررسی طی چند ساعت انجام می‌شود.',
        'vip_approved': '🎉 **تبریک! اشتراک VIP شما فعال شد.**\n\n📦 پلن: {plan}\n\nحالا به سیگنال نامحدود و همه‌ی امکانات VIP دسترسی دارید. برای مشاهده‌ی جزئیات به «تنظیمات» مراجعه کنید.',
        'vip_rejected': '❌ **درخواست پرداخت VIP شما تایید نشد.**\n\nاگر فکر می‌کنید اشتباهی رخ داده، لطفاً با پشتیبانی (@RealSurprise) در تماس باشید.',
        'vip_status_active': '👑 **VIP فعال** ({plan}) — {days_left} روز باقی‌مانده',
        'vip_status_none': '🔓 عادی (VIP نیستید)',
        'settings_text': '⚙️ **تنظیمات**\n\n🔹 **وضعیت:** {status}\n🔹 **سبک:** {style}\n🔹 **زبان:** {lang}\n\n📊 **سیگنال باقی‌مانده امروز:** {signals_left}\n{vip_line}',
        'pnl_calc_btn': '📈 محاسبه‌ی سود بر اساس ریسک ثابت',
        'pnl_ask_risk': '💰 **درصد ریسک ثابت هر معامله**\n\nچند درصد از سرمایه‌تان را در هر معامله ریسک می‌کنید؟\n\nعدد را وارد کنید (مثال: `1.5` برای ۱.۵٪ یا `2` برای ۲٪):',
        'pnl_invalid_risk': '❌ لطفاً یک عدد معتبر بین ۰ تا ۱۰۰ وارد کنید (مثال: `1.5`).',
        'pnl_no_trades': '📭 در این بازه‌ی زمانی معامله‌ی بسته‌شده‌ای (TP/SL) ثبت نشده است.',
        'pnl_result_text': '📈 **گزارش سود/زیان — {period}**\n\n💰 ریسک هر معامله: {risk_percent}٪\n📊 تعداد کل معاملات: {total} (✅ {wins} · ❌ {losses})\n🎯 وین‌ریت: {winrate}٪\n\n📈 مجموع سود: +{profit_percent}٪\n📉 مجموع ضرر: -{loss_percent}٪\n💵 **سود خالص: {net_percent}٪**\n\n⚖️ **Profit Factor: {profit_factor}**\n_(نسبت مجموع سود به مجموع ضرر - بالاتر از ۱ یعنی سودآور)_',
        'online': 'آنلاین',
        'offline': 'آفلاین',
        'not_selected_yet': 'هنوز انتخاب نشده',
        'referral_text': '👥 **سیستم رفرال**\n\nلینک رفرال شما:\n`{link}`\n\nبه ازای هر ۵ رفرال، ۱ سیگنال اضافی دریافت میکنید.',
        'support_text': '🆘 **پشتیبانی**\n\n👤 **ایدی:** {support}\n⏰ **ساعت پاسخگویی:** ۲۴ ساعته',
        'dashboard_btn': '📊 Dashboard',
        'users_btn': '👥 Users',
        'analytics_btn': '📈 Analytics',
        'set_daily_signal_btn': '📊 Set Daily Signal',
        'set_rr_btn': '🎯 Set RR Ratio',
        'set_timeframe_btn': '⏱️ Set Timeframe',
        'referral_bonus_btn': '👥 Referral Bonus',
        'referral_threshold_btn': '🎯 Referral Threshold',
        'reset_signals_btn': '🔄 Reset Signals',
        'bot_lock_btn': '🔒 Bot Lock',
        'signal_control_btn': '🚀 Signal Control',
        'channel_lock_btn': '🔒 Channel Lock',
        'vip_user_btn': '👑 VIP User',
        'delete_user_btn': '🗑️ Delete User',
        'broadcast_btn': '📢 Broadcast',
        'reports_btn': '📊 Reports'
    },
    'en': {
        'name': 'English',
        'select_style': '📊 **Select your trading style:**',
        'select_mode': '🌀 **Select Surpri3e Strategy mode:**',
        'select_timeframe': '⏱️ **Select timeframe:**',
        'select_rr': '🎯 **Select Risk/Reward Ratio (RR):**',
        'change_lang': '🌍 Change Language',
        'tf_1min': '1 min',
        'tf_5min': '5 min',
        'tf_15min': '15 min',
        'tf_1h': '1 hour',
        'tf_4h': '4 hours',
        'tf_1d': '1 day',
        'signal_btn': '🚨 Get Signal',
        'performance_btn': '📊 Performance',
        'history_btn': '📜 History',
        'price_btn': '💰 Live Price',
        'vip_btn': '💎 VIP',
        'referral_btn': '👥 Referral',
        'settings_btn': '⚙️ Settings',
        'support_btn': '🆘 Support',
        'back_btn': '🔙 Back',
        'copy_link': '📤 Copy Link',
        'tp_btn': '✅ TP HIT',
        'sl_btn': '❌ SL HIT',
        'cancel_btn': '🚫 CANCEL',
        'signal_title': 'New Signal',
        'style_label': 'Style',
        'direction_label': 'Direction',
        'entry_label': 'Entry',
        'sl_label': 'Stop Loss',
        'tp_label': 'Take Profit',
        'rr_label': 'RR Ratio',
        'reasons_label': 'Reasons',
        'timeframe_label': 'Timeframe',
        'price_label': 'Live Price',
        'time_label': 'Tehran Time',
        'result_label': 'Select trade result',
        'tp_registered': '✅ **TP registered**\n\nUse the buttons below to continue:',
        'sl_registered': '❌ **SL registered**\n\nUse the buttons below to continue:',
        'canceled': '🚫 **Signal canceled**\n\nUse the buttons below to continue:',
        'no_signal': '❌ **No signal found**',
        'error': 'Error',
        'welcome_back': '🤖 **Welcome back**',
        'fetching_price': '💰 **Fetching price...**',
        'price_result': '💰 **Live Gold Price**\n\n📊 XAU/USD\n\n💵 Price: {price:.2f} USD\n🕐 Time: {time}',
        'price_error': '❌ **Error fetching price**\n\nPlease try again.',
        'signal_disabled': '⛔ **Signal disabled.**',
        'no_signals_left': '❌ **Daily signal limit reached!**\nWait until tomorrow or increase via referrals.',
        'signal_cooldown': '⏱️ **Too soon!**\nFor {timeframe} timeframe, wait {wait} more for the new candle to close.',
        'market_closed': '🌙 **The gold market (XAU/USD) is currently closed.**\n\nThe forex/gold market is closed from Friday evening to Sunday evening (UTC). Please try again once the market reopens.',
        'loading_frame_1': '🔍 Analyzing market structure.',
        'loading_frame_2': '🔍 Analyzing market structure..',
        'loading_frame_3': '📊 Checking pivot points and liquidity zones...',
        'loading_frame_4': '🧠 Finalizing the signal....',
        'analyzing': '🔍 **Analyzing ({timeframe})...**',
        'use_buttons': '❌ **Please use the buttons!**',
        'performance_text': '📊 **Your Performance**\n\n🗓️ **This week:** {weekly_wins} wins out of {weekly_total} trades ({weekly_winrate}%)\n📅 **This month:** {monthly_wins} wins out of {monthly_total} trades ({monthly_winrate}%)\n\n📈 **Total closed trades:** {total}\n✅ **Wins:** {wins}\n❌ **Losses:** {losses}\n🎯 **Overall winrate:** {winrate}%\n\n📊 **Left today:** {left}',
        'performance_menu_text': '📊 **Performance**\n\nTo see your winrate stats (based on trades where you marked TP or SL yourself), choose a period below:\n\n📊 **Left today:** {left}',
        'weekly_btn': '🗓️ Weekly Performance',
        'monthly_btn': '📅 Monthly Performance',
        'weekly_performance_text': '🗓️ **Your Weekly Performance**\n\n📈 **Total closed trades:** {total}\n✅ **Wins (TP):** {wins}\n❌ **Losses (SL):** {losses}\n🎯 **Winrate:** {winrate}%\n\n_Based on trades you marked TP or SL yourself in the last 7 days._',
        'monthly_performance_text': '📅 **Your Monthly Performance**\n\n📈 **Total closed trades:** {total}\n✅ **Wins (TP):** {wins}\n❌ **Losses (SL):** {losses}\n🎯 **Winrate:** {winrate}%\n\n_Based on trades you marked TP or SL yourself in the last 30 days._',
        'history_title': '📜 **Trade History:**',
        'no_history': '📭 **No trades yet!**',
        'vip_intro_text': "💎 **Surpri3e VIP Membership**\n\nAccess to all plans and unlimited signals — no daily cap, no waiting.\n\n⚡ Unlimited signals on every timeframe\n🌀 Priority access to Surpri3e strategy analysis\n📊 Full access to detailed performance reports\n🎯 Custom RR on every trade\n🆘 Dedicated priority support\n\nChoose one of the plans below:",
        'vip_plan_btn_1m': '🥉 1 Month — 500,000 Toman',
        'vip_plan_btn_3m': '🥈 3 Months — 1,400,000 Toman',
        'vip_plan_btn_6m': '🥇 6 Months — 2,900,000 Toman',
        'vip_plan_btn_12m': '💎 12 Months — 4,800,000 Toman',
        'vip_payment_card_text': '💳 **Payment for {plan} plan**\n\nAmount due: **{price:,} Toman**\n\nPlease transfer to the card number below:\n`{card_number}`\n{card_holder_line}\n\nOnce paid, tap the button below to continue.',
        'vip_card_not_set': "⚠️ The card number hasn't been set by the admin yet. Please try again later or contact support.",
        'vip_paid_btn': "✅ I've Paid",
        'vip_ask_phone': '📞 **Phone number**\n\nPlease send your phone number to follow up on the payment (e.g. `09121234567`):',
        'vip_invalid_phone': '❌ Invalid phone number. Please send a valid one (e.g. `09121234567`).',
        'vip_ask_receipt': '🧾 **Payment receipt**\n\nPlease send a photo of your payment receipt here:',
        'vip_receipt_not_photo': '❌ Please send the receipt as a **photo**, not a file or text.',
        'vip_request_submitted': "✅ **Your request has been submitted!**\n\nYour receipt and details were sent to the admin for review. Once approved, your VIP subscription will be activated and you'll be notified.\n\n⏳ This usually takes a few hours.",
        'vip_approved': '🎉 **Congratulations! Your VIP subscription is now active.**\n\n📦 Plan: {plan}\n\nYou now have unlimited signals and full VIP access. Check "Settings" for details.',
        'vip_rejected': "❌ **Your VIP payment request was not approved.**\n\nIf you think this is a mistake, please contact support (@RealSurprise).",
        'vip_status_active': '👑 **VIP Active** ({plan}) — {days_left} days left',
        'vip_status_none': '🔓 Standard (not VIP)',
        'settings_text': '⚙️ **Settings**\n\n🔹 **Status:** {status}\n🔹 **Style:** {style}\n🔹 **Language:** {lang}\n\n📊 **Signals left today:** {signals_left}\n{vip_line}',
        'pnl_calc_btn': '📈 Calculate P&L by Fixed Risk',
        'pnl_ask_risk': '💰 **Fixed risk per trade**\n\nWhat percentage of your capital do you risk on each trade?\n\nEnter a number (e.g. `1.5` for 1.5% or `2` for 2%):',
        'pnl_invalid_risk': '❌ Please enter a valid number between 0 and 100 (e.g. `1.5`).',
        'pnl_no_trades': '📭 No closed trades (TP/SL) found in this period.',
        'pnl_result_text': '📈 **P&L Report — {period}**\n\n💰 Risk per trade: {risk_percent}%\n📊 Total trades: {total} (✅ {wins} · ❌ {losses})\n🎯 Win rate: {winrate}%\n\n📈 Total profit: +{profit_percent}%\n📉 Total loss: -{loss_percent}%\n💵 **Net P&L: {net_percent}%**\n\n⚖️ **Profit Factor: {profit_factor}**\n_(Ratio of total profit to total loss — above 1 means profitable)_',
        'online': 'Online',
        'offline': 'Offline',
        'not_selected_yet': 'Not selected yet',
        'referral_text': '👥 **Referral System**\n\nYour referral link:\n`{link}`\n\nFor every 5 referrals, you get 1 extra signal.',
        'support_text': '🆘 **Support**\n\n👤 **ID:** {support}\n⏰ **Response time:** 24/7',
        'dashboard_btn': '📊 Dashboard',
        'users_btn': '👥 Users',
        'analytics_btn': '📈 Analytics',
        'set_daily_signal_btn': '📊 Set Daily Signal',
        'set_rr_btn': '🎯 Set RR Ratio',
        'set_timeframe_btn': '⏱️ Set Timeframe',
        'referral_bonus_btn': '👥 Referral Bonus',
        'referral_threshold_btn': '🎯 Referral Threshold',
        'reset_signals_btn': '🔄 Reset Signals',
        'bot_lock_btn': '🔒 Bot Lock',
        'signal_control_btn': '🚀 Signal Control',
        'channel_lock_btn': '🔒 Channel Lock',
        'vip_user_btn': '👑 VIP User',
        'delete_user_btn': '🗑️ Delete User',
        'broadcast_btn': '📢 Broadcast',
        'reports_btn': '📊 Reports'
    },
}


def get_text(lang, key):
    """دریافت متن بر اساس زبان"""
    if lang not in LANGUAGES:
        lang = 'fa'
    return LANGUAGES[lang].get(key, key)
