# languages.py

LANGUAGES = {
    'fa': {
        'name': 'فارسی',
        'select_style': '📊 **سبک معاملاتی خود را انتخاب کنید:**',
        'select_mode': '🌀 **حالت معاملاتی Surpri3e Strategy را انتخاب کنید:**',
        'select_timeframe': '⏱️ **تایم‌فریم را انتخاب کنید:**',
        'select_rr': '🎯 **نسبت ریسک به ریوارد (RR) را انتخاب کنید:**',
        'change_lang': '🌍 تغییر زبان',
        'tf_1min': '1 دقیقه',
        'tf_5min': '5 دقیقه',
        'tf_15min': '15 دقیقه',
        'tf_1h': '1 ساعت',
        'tf_4h': '4 ساعت',
        'tf_1d': '1 روز',
        'signal_btn': '🚨 دریافت سیگنال',
        'performance_btn': '📊 عملکرد',
        'history_btn': '📜 تاریخچه',
        'price_btn': '💰 قیمت لحظه‌ای',
        'vip_btn': '💎 VIP',
        'referral_btn': '👥 رفرال',
        'settings_btn': '⚙️ تنظیمات',
        'support_btn': '🆘 پشتیبانی',
        'back_btn': '🔙 برگشت',
        'copy_link': '📤 کپی لینک',
        'tp_btn': '✅ TP HIT',
        'sl_btn': '❌ SL HIT',
        'cancel_btn': '🚫 CANCEL',
        'signal_title': 'سیگنال جدید',
        'style_label': 'سبک',
        'direction_label': 'جهت',
        'entry_label': 'ورود',
        'sl_label': 'حد ضرر',
        'tp_label': 'حد سود',
        'rr_label': 'نسبت RR',
        'reasons_label': 'دلایل',
        'timeframe_label': 'تایم‌فریم',
        'price_label': 'قیمت لحظه‌ای',
        'time_label': 'زمان تهران',
        'result_label': 'نتیجه معامله را انتخاب کنید',
        'tp_registered': '✅ **TP ثبت شد**\n\nبرای ادامه از دکمه‌های زیر استفاده کنید:',
        'sl_registered': '❌ **SL ثبت شد**\n\nبرای ادامه از دکمه‌های زیر استفاده کنید:',
        'canceled': '🚫 **سیگنال لغو شد**\n\nبرای ادامه از دکمه‌های زیر استفاده کنید:',
        'no_signal': '❌ **سیگنالی پیدا نشد**',
        'error': 'خطا',
        'welcome_back': '🤖 **به پنل خوش آمدید**',
        'fetching_price': '💰 **در حال دریافت قیمت...**',
        'price_result': '💰 **قیمت لحظه‌ای طلا**\n\n📊 XAU/USD\n\n💵 قیمت: {price:.2f} USD\n🕐 زمان تهران: {time}',
        'price_error': '❌ **خطا در دریافت قیمت**\n\nلطفاً دوباره تلاش کنید.',
        'signal_disabled': '⛔ **سیگنال‌دهی غیرفعال است.**',
        'no_signals_left': '❌ **تعداد سیگنال روزانه شما تمام شده!**\nصبر کنید تا فردا یا از طریق رفرال افزایش دهید.',
        'signal_cooldown': '⏱️ **کمی زود است!**\nبرای تایم‌فریم {timeframe} باید {wait} دیگر صبر کنید تا کندل جدید ببندد.',
        'market_closed': '🌙 **بازار طلا (XAU/USD) هم‌اکنون بسته است.**\n\nبازار فارکس/طلا از جمعه شب تا یکشنبه شب (به وقت جهانی) تعطیل است. لطفاً پس از بازگشایی بازار دوباره تلاش کنید.',
        'loading_frame_1': '🔍 در حال بررسی ساختار بازار.',
        'loading_frame_2': '🔍 در حال بررسی ساختار بازار..',
        'loading_frame_3': '📊 در حال تحلیل نقاط چرخش و نواحی نقدینگی...',
        'loading_frame_4': '🧠 در حال جمع‌بندی نهایی سیگنال....',
        'analyzing': '🔍 **در حال تحلیل ({timeframe})...**',
        'use_buttons': '❌ **لطفاً از دکمه‌ها استفاده کنید!**',
        'performance_text': '📊 **آمار عملکرد شما**\n\n🗓️ **این هفته:** {weekly_wins} برد از {weekly_total} معامله ({weekly_winrate}%)\n📅 **این ماه:** {monthly_wins} برد از {monthly_total} معامله ({monthly_winrate}%)\n\n📈 **کل معاملات بسته‌شده:** {total}\n✅ **برنده:** {wins}\n❌ **بازنده:** {losses}\n🎯 **نرخ موفقیت کلی:** {winrate}%\n\n📊 **سیگنال باقی‌مانده امروز:** {left}',
        'performance_menu_text': '📊 **بخش عملکرد**\n\nبرای مشاهده‌ی آمار وین‌ریت خودتان (بر اساس معاملاتی که خودتان TP یا SL را ثبت کرده‌اید)، یکی از بازه‌های زیر را انتخاب کنید:\n\n📊 **سیگنال باقی‌مانده امروز:** {left}',
        'weekly_btn': '🗓️ عملکرد هفتگی',
        'monthly_btn': '📅 عملکرد ماهانه',
        'weekly_performance_text': '🗓️ **عملکرد هفتگی شما**\n\n📈 **کل معاملات بسته‌شده:** {total}\n✅ **برنده (TP):** {wins}\n❌ **بازنده (SL):** {losses}\n🎯 **نرخ موفقیت:** {winrate}%\n\n_بر اساس معاملاتی که خودتان طی ۷ روز اخیر TP یا SL را ثبت کرده‌اید._',
        'monthly_performance_text': '📅 **عملکرد ماهانه شما**\n\n📈 **کل معاملات بسته‌شده:** {total}\n✅ **برنده (TP):** {wins}\n❌ **بازنده (SL):** {losses}\n🎯 **نرخ موفقیت:** {winrate}%\n\n_بر اساس معاملاتی که خودتان طی ۳۰ روز اخیر TP یا SL را ثبت کرده‌اید._',
        'history_title': '📜 **تاریخچه معاملات:**',
        'no_history': '📭 **هنوز معامله‌ای ندارید!**',
        'vip_text': '💎 **پنل VIP**\n\n✅ **سیگنال‌های ویژه**\n✅ **آنالیز پیشرفته**\n✅ **پشتیبانی اختصاصی**\n\n👤 @RealSurprise',
        'settings_text': '⚙️ **تنظیمات**\n\n🔹 **تایم‌فریم:** {timeframe}\n🔹 **وضعیت:** {status}\n🔹 **RR:** 1:{rr}\n🔹 **سبک:** {style}\n🔹 **زبان:** {lang}',
        'online': 'آنلاین',
        'offline': 'آفلاین',
        'referral_text': '👥 **سیستم رفرال**\n\nلینک رفرال شما:\n`{link}`\n\nبه ازای هر ۵ رفرال، ۱ سیگنال اضافی دریافت میکنید.',
        'support_text': '🆘 **پشتیبانی**\n\n👤 **ایدی:** {support}\n⏰ **ساعت پاسخگویی:** ۲۴ ساعته',
        'dashboard_btn': '📊 Dashboard',
        'users_btn': '👥 Users',
        'analytics_btn': '📈 Analytics',
        'set_daily_signal_btn': '📊 Set Daily Signal',
        'set_rr_btn': '🎯 Set RR Ratio',
        'set_timeframe_btn': '⏱️ Set Timeframe',
        'referral_bonus_btn': '👥 Referral Bonus',
        'referral_threshold_btn': '🎯 Referral Threshold',
        'reset_signals_btn': '🔄 Reset Signals',
        'bot_lock_btn': '🔒 Bot Lock',
        'signal_control_btn': '🚀 Signal Control',
        'channel_lock_btn': '🔒 Channel Lock',
        'vip_user_btn': '👑 VIP User',
        'delete_user_btn': '🗑️ Delete User',
        'broadcast_btn': '📢 Broadcast',
        'reports_btn': '📊 Reports'
    },
    'en': {
        'name': 'English',
        'select_style': '📊 **Select your trading style:**',
        'select_mode': '🌀 **Select Surpri3e Strategy mode:**',
        'select_timeframe': '⏱️ **Select timeframe:**',
        'select_rr': '🎯 **Select Risk/Reward Ratio (RR):**',
        'change_lang': '🌍 Change Language',
        'tf_1min': '1 min',
        'tf_5min': '5 min',
        'tf_15min': '15 min',
        'tf_1h': '1 hour',
        'tf_4h': '4 hours',
        'tf_1d': '1 day',
        'signal_btn': '🚨 Get Signal',
        'performance_btn': '📊 Performance',
        'history_btn': '📜 History',
        'price_btn': '💰 Live Price',
        'vip_btn': '💎 VIP',
        'referral_btn': '👥 Referral',
        'settings_btn': '⚙️ Settings',
        'support_btn': '🆘 Support',
        'back_btn': '🔙 Back',
        'copy_link': '📤 Copy Link',
        'tp_btn': '✅ TP HIT',
        'sl_btn': '❌ SL HIT',
        'cancel_btn': '🚫 CANCEL',
        'signal_title': 'New Signal',
        'style_label': 'Style',
        'direction_label': 'Direction',
        'entry_label': 'Entry',
        'sl_label': 'Stop Loss',
        'tp_label': 'Take Profit',
        'rr_label': 'RR Ratio',
        'reasons_label': 'Reasons',
        'timeframe_label': 'Timeframe',
        'price_label': 'Live Price',
        'time_label': 'Tehran Time',
        'result_label': 'Select trade result',
        'tp_registered': '✅ **TP registered**\n\nUse the buttons below to continue:',
        'sl_registered': '❌ **SL registered**\n\nUse the buttons below to continue:',
        'canceled': '🚫 **Signal canceled**\n\nUse the buttons below to continue:',
        'no_signal': '❌ **No signal found**',
        'error': 'Error',
        'welcome_back': '🤖 **Welcome back**',
        'fetching_price': '💰 **Fetching price...**',
        'price_result': '💰 **Live Gold Price**\n\n📊 XAU/USD\n\n💵 Price: {price:.2f} USD\n🕐 Time: {time}',
        'price_error': '❌ **Error fetching price**\n\nPlease try again.',
        'signal_disabled': '⛔ **Signal disabled.**',
        'no_signals_left': '❌ **Daily signal limit reached!**\nWait until tomorrow or increase via referrals.',
        'signal_cooldown': '⏱️ **Too soon!**\nFor {timeframe} timeframe, wait {wait} more for the new candle to close.',
        'market_closed': '🌙 **The gold market (XAU/USD) is currently closed.**\n\nThe forex/gold market is closed from Friday evening to Sunday evening (UTC). Please try again once the market reopens.',
        'loading_frame_1': '🔍 Analyzing market structure.',
        'loading_frame_2': '🔍 Analyzing market structure..',
        'loading_frame_3': '📊 Checking pivot points and liquidity zones...',
        'loading_frame_4': '🧠 Finalizing the signal....',
        'analyzing': '🔍 **Analyzing ({timeframe})...**',
        'use_buttons': '❌ **Please use the buttons!**',
        'performance_text': '📊 **Your Performance**\n\n🗓️ **This week:** {weekly_wins} wins out of {weekly_total} trades ({weekly_winrate}%)\n📅 **This month:** {monthly_wins} wins out of {monthly_total} trades ({monthly_winrate}%)\n\n📈 **Total closed trades:** {total}\n✅ **Wins:** {wins}\n❌ **Losses:** {losses}\n🎯 **Overall winrate:** {winrate}%\n\n📊 **Left today:** {left}',
        'performance_menu_text': '📊 **Performance**\n\nTo see your winrate stats (based on trades where you marked TP or SL yourself), choose a period below:\n\n📊 **Left today:** {left}',
        'weekly_btn': '🗓️ Weekly Performance',
        'monthly_btn': '📅 Monthly Performance',
        'weekly_performance_text': '🗓️ **Your Weekly Performance**\n\n📈 **Total closed trades:** {total}\n✅ **Wins (TP):** {wins}\n❌ **Losses (SL):** {losses}\n🎯 **Winrate:** {winrate}%\n\n_Based on trades you marked TP or SL yourself in the last 7 days._',
        'monthly_performance_text': '📅 **Your Monthly Performance**\n\n📈 **Total closed trades:** {total}\n✅ **Wins (TP):** {wins}\n❌ **Losses (SL):** {losses}\n🎯 **Winrate:** {winrate}%\n\n_Based on trades you marked TP or SL yourself in the last 30 days._',
        'history_title': '📜 **Trade History:**',
        'no_history': '📭 **No trades yet!**',
        'vip_text': '💎 **VIP Panel**\n\n✅ **Special Signals**\n✅ **Advanced Analysis**\n✅ **Dedicated Support**\n\n👤 @RealSurprise',
        'settings_text': '⚙️ **Settings**\n\n🔹 **Timeframe:** {timeframe}\n🔹 **Status:** {status}\n🔹 **RR:** 1:{rr}\n🔹 **Style:** {style}\n🔹 **Language:** {lang}',
        'online': 'Online',
        'offline': 'Offline',
        'referral_text': '👥 **Referral System**\n\nYour referral link:\n`{link}`\n\nFor every 5 referrals, you get 1 extra signal.',
        'support_text': '🆘 **Support**\n\n👤 **ID:** {support}\n⏰ **Response time:** 24/7',
        'dashboard_btn': '📊 Dashboard',
        'users_btn': '👥 Users',
        'analytics_btn': '📈 Analytics',
        'set_daily_signal_btn': '📊 Set Daily Signal',
        'set_rr_btn': '🎯 Set RR Ratio',
        'set_timeframe_btn': '⏱️ Set Timeframe',
        'referral_bonus_btn': '👥 Referral Bonus',
        'referral_threshold_btn': '🎯 Referral Threshold',
        'reset_signals_btn': '🔄 Reset Signals',
        'bot_lock_btn': '🔒 Bot Lock',
        'signal_control_btn': '🚀 Signal Control',
        'channel_lock_btn': '🔒 Channel Lock',
        'vip_user_btn': '👑 VIP User',
        'delete_user_btn': '🗑️ Delete User',
        'broadcast_btn': '📢 Broadcast',
        'reports_btn': '📊 Reports'
    },
    'ru': {
        'name': 'Русский',
        'select_style': '📊 **Выберите стиль торговли:**',
        'select_mode': '🌀 **Выберите режим Surpri3e Strategy:**',
        'select_timeframe': '⏱️ **Выберите таймфрейм:**',
        'select_rr': '🎯 **Выберите соотношение Риск/Прибыль (RR):**',
        'change_lang': '🌍 Сменить язык',
        'tf_1min': '1 минута',
        'tf_5min': '5 минут',
        'tf_15min': '15 минут',
        'tf_1h': '1 час',
        'tf_4h': '4 часа',
        'tf_1d': '1 день',
        'signal_btn': '🚨 Получить сигнал',
        'performance_btn': '📊 Производительность',
        'history_btn': '📜 История',
        'price_btn': '💰 Цена',
        'vip_btn': '💎 VIP',
        'referral_btn': '👥 Рефералы',
        'settings_btn': '⚙️ Настройки',
        'support_btn': '🆘 Поддержка',
        'back_btn': '🔙 Назад',
        'copy_link': '📤 Копировать ссылку',
        'tp_btn': '✅ TP HIT',
        'sl_btn': '❌ SL HIT',
        'cancel_btn': '🚫 ОТМЕНА',
        'signal_title': 'Новый сигнал',
        'style_label': 'Стиль',
        'direction_label': 'Направление',
        'entry_label': 'Вход',
        'sl_label': 'Стоп-лосс',
        'tp_label': 'Тейк-профит',
        'rr_label': 'Соотношение RR',
        'reasons_label': 'Причины',
        'timeframe_label': 'Таймфрейм',
        'price_label': 'Цена',
        'time_label': 'Время Тегеран',
        'result_label': 'Выберите результат сделки',
        'tp_registered': '✅ **TP зарегистрирован**\n\nИспользуйте кнопки ниже для продолжения:',
        'sl_registered': '❌ **SL зарегистрирован**\n\nИспользуйте кнопки ниже для продолжения:',
        'canceled': '🚫 **Сигнал отменён**\n\nИспользуйте кнопки ниже для продолжения:',
        'no_signal': '❌ **Сигнал не найден**',
        'error': 'Ошибка',
        'welcome_back': '🤖 **Добро пожаловать**',
        'fetching_price': '💰 **Получение цены...**',
        'price_result': '💰 **Текущая цена золота**\n\n📊 XAU/USD\n\n💵 Цена: {price:.2f} USD\n🕐 Время: {time}',
        'price_error': '❌ **Ошибка получения цены**\n\nПожалуйста, попробуйте снова.',
        'signal_disabled': '⛔ **Сигналы отключены.**',
        'no_signals_left': '❌ **Дневной лимит сигналов исчерпан!**\nПодождите до завтра или увеличьте через рефералов.',
        'signal_cooldown': '⏱️ **Слишком рано!**\nДля таймфрейма {timeframe} подождите ещё {wait} до закрытия новой свечи.',
        'market_closed': '🌙 **Рынок золота (XAU/USD) сейчас закрыт.**\n\nРынок форекс/золота закрыт с вечера пятницы до вечера воскресенья (UTC). Попробуйте снова после открытия рынка.',
        'loading_frame_1': '🔍 Анализ структуры рынка.',
        'loading_frame_2': '🔍 Анализ структуры рынка..',
        'loading_frame_3': '📊 Проверка точек разворота и зон ликвидности...',
        'loading_frame_4': '🧠 Финализация сигнала....',
        'analyzing': '🔍 **Анализ ({timeframe})...**',
        'use_buttons': '❌ **Пожалуйста, используйте кнопки!**',
        'performance_text': '📊 **Ваша статистика**\n\n🗓️ **За неделю:** {weekly_wins} побед из {weekly_total} сделок ({weekly_winrate}%)\n📅 **За месяц:** {monthly_wins} побед из {monthly_total} сделок ({monthly_winrate}%)\n\n📈 **Всего закрытых сделок:** {total}\n✅ **Выигрыши:** {wins}\n❌ **Проигрыши:** {losses}\n🎯 **Общий процент успеха:** {winrate}%\n\n📊 **Осталось сегодня:** {left}',
        'performance_menu_text': '📊 **Производительность**\n\nЧтобы увидеть статистику winrate (на основе сделок, где вы сами отметили TP или SL), выберите период:\n\n📊 **Осталось сегодня:** {left}',
        'weekly_btn': '🗓️ Недельная статистика',
        'monthly_btn': '📅 Месячная статистика',
        'weekly_performance_text': '🗓️ **Ваша недельная статистика**\n\n📈 **Всего закрытых сделок:** {total}\n✅ **Выигрыши (TP):** {wins}\n❌ **Проигрыши (SL):** {losses}\n🎯 **Процент успеха:** {winrate}%\n\n_На основе сделок, отмеченных вами за последние 7 дней._',
        'monthly_performance_text': '📅 **Ваша месячная статистика**\n\n📈 **Всего закрытых сделок:** {total}\n✅ **Выигрыши (TP):** {wins}\n❌ **Проигрыши (SL):** {losses}\n🎯 **Процент успеха:** {winrate}%\n\n_На основе сделок, отмеченных вами за последние 30 дней._',
        'history_title': '📜 **История сделок:**',
        'no_history': '📭 **Нет сделок!**',
        'vip_text': '💎 **VIP панель**\n\n✅ **Специальные сигналы**\n✅ **Расширенный анализ**\n✅ **Поддержка**\n\n👤 @RealSurprise',
        'settings_text': '⚙️ **Настройки**\n\n🔹 **Таймфрейм:** {timeframe}\n🔹 **Статус:** {status}\n🔹 **RR:** 1:{rr}\n🔹 **Стиль:** {style}\n🔹 **Язык:** {lang}',
        'online': 'Онлайн',
        'offline': 'Офлайн',
        'referral_text': '👥 **Реферальная система**\n\nВаша ссылка:\n`{link}`\n\nЗа каждые 5 рефералов вы получаете 1 дополнительный сигнал.',
        'support_text': '🆘 **Поддержка**\n\n👤 **ID:** {support}\n⏰ **Время ответа:** 24/7',
        'dashboard_btn': '📊 Dashboard',
        'users_btn': '👥 Users',
        'analytics_btn': '📈 Analytics',
        'set_daily_signal_btn': '📊 Set Daily Signal',
        'set_rr_btn': '🎯 Set RR Ratio',
        'set_timeframe_btn': '⏱️ Set Timeframe',
        'referral_bonus_btn': '👥 Referral Bonus',
        'referral_threshold_btn': '🎯 Referral Threshold',
        'reset_signals_btn': '🔄 Reset Signals',
        'bot_lock_btn': '🔒 Bot Lock',
        'signal_control_btn': '🚀 Signal Control',
        'channel_lock_btn': '🔒 Channel Lock',
        'vip_user_btn': '👑 VIP User',
        'delete_user_btn': '🗑️ Delete User',
        'broadcast_btn': '📢 Broadcast',
        'reports_btn': '📊 Reports'
    },
    'ar': {
        'name': 'العربية',
        'select_style': '📊 **اختر نمط التداول الخاص بك:**',
        'select_mode': '🌀 **اختر وضع Surpri3e Strategy:**',
        'select_timeframe': '⏱️ **اختر الإطار الزمني:**',
        'select_rr': '🎯 **اختر نسبة المخاطرة/المكافأة (RR):**',
        'change_lang': '🌍 تغيير اللغة',
        'tf_1min': 'دقيقة 1',
        'tf_5min': 'دقائق 5',
        'tf_15min': 'دقائق 15',
        'tf_1h': 'ساعة 1',
        'tf_4h': 'ساعات 4',
        'tf_1d': 'يوم 1',
        'signal_btn': '🚨 الحصول على إشارة',
        'performance_btn': '📊 الأداء',
        'history_btn': '📜 التاريخ',
        'price_btn': '💰 السعر اللحظي',
        'vip_btn': '💎 VIP',
        'referral_btn': '👥 الإحالة',
        'settings_btn': '⚙️ الإعدادات',
        'support_btn': '🆘 الدعم',
        'back_btn': '🔙 رجوع',
        'copy_link': '📤 نسخ الرابط',
        'tp_btn': '✅ TP HIT',
        'sl_btn': '❌ SL HIT',
        'cancel_btn': '🚫 إلغاء',
        'signal_title': 'إشارة جديدة',
        'style_label': 'النمط',
        'direction_label': 'الاتجاه',
        'entry_label': 'الدخول',
        'sl_label': 'وقف الخسارة',
        'tp_label': 'جني الأرباح',
        'rr_label': 'نسبة RR',
        'reasons_label': 'الأسباب',
        'timeframe_label': 'الإطار الزمني',
        'price_label': 'السعر اللحظي',
        'time_label': 'توقيت طهران',
        'result_label': 'اختر نتيجة الصفقة',
        'tp_registered': '✅ **تم تسجيل TP**\n\nاستخدم الأزرار أدناه للمتابعة:',
        'sl_registered': '❌ **تم تسجيل SL**\n\nاستخدم الأزرار أدناه للمتابعة:',
        'canceled': '🚫 **تم إلغاء الإشارة**\n\nاستخدم الأزرار أدناه للمتابعة:',
        'no_signal': '❌ **لم يتم العثور على إشارة**',
        'error': 'خطأ',
        'welcome_back': '🤖 **مرحباً بك**',
        'fetching_price': '💰 **جاري الحصول على السعر...**',
        'price_result': '💰 **سعر الذهب اللحظي**\n\n📊 XAU/USD\n\n💵 السعر: {price:.2f} USD\n🕐 الوقت: {time}',
        'price_error': '❌ **خطأ في الحصول على السعر**\n\nيرجى المحاولة مرة أخرى.',
        'signal_disabled': '⛔ **الإشارات معطلة.**',
        'no_signals_left': '❌ **تم الوصول إلى الحد اليومي للإشارات!**\nانتظر حتى الغد أو قم بالزيادة عبر الإحالات.',
        'signal_cooldown': '⏱️ **مبكر جداً!**\nللإطار الزمني {timeframe}، انتظر {wait} أخرى حتى تُغلق الشمعة الجديدة.',
        'market_closed': '🌙 **سوق الذهب (XAU/USD) مغلق حالياً.**\n\nسوق الفوركس/الذهب مغلق من مساء الجمعة حتى مساء الأحد (بتوقيت UTC). يرجى المحاولة مرة أخرى بعد إعادة فتح السوق.',
        'loading_frame_1': '🔍 جاري تحليل هيكل السوق.',
        'loading_frame_2': '🔍 جاري تحليل هيكل السوق..',
        'loading_frame_3': '📊 جاري فحص نقاط الانعكاس ومناطق السيولة...',
        'loading_frame_4': '🧠 جاري إنهاء الإشارة....',
        'analyzing': '🔍 **جاري التحليل ({timeframe})...**',
        'use_buttons': '❌ **يرجى استخدام الأزرار!**',
        'performance_text': '📊 **أداؤك**\n\n🗓️ **هذا الأسبوع:** {weekly_wins} ربح من {weekly_total} صفقة ({weekly_winrate}%)\n📅 **هذا الشهر:** {monthly_wins} ربح من {monthly_total} صفقة ({monthly_winrate}%)\n\n📈 **إجمالي الصفقات المغلقة:** {total}\n✅ **الفوز:** {wins}\n❌ **الخسارة:** {losses}\n🎯 **نسبة النجاح الإجمالية:** {winrate}%\n\n📊 **المتبقي اليوم:** {left}',
        'performance_menu_text': '📊 **الأداء**\n\nلمشاهدة إحصائيات نسبة النجاح (بناءً على الصفقات التي حددتها بنفسك كـ TP أو SL)، اختر فترة:\n\n📊 **المتبقي اليوم:** {left}',
        'weekly_btn': '🗓️ الأداء الأسبوعي',
        'monthly_btn': '📅 الأداء الشهري',
        'weekly_performance_text': '🗓️ **أداؤك الأسبوعي**\n\n📈 **إجمالي الصفقات المغلقة:** {total}\n✅ **الفوز (TP):** {wins}\n❌ **الخسارة (SL):** {losses}\n🎯 **نسبة النجاح:** {winrate}%\n\n_بناءً على الصفقات التي حددتها بنفسك خلال آخر 7 أيام._',
        'monthly_performance_text': '📅 **أداؤك الشهري**\n\n📈 **إجمالي الصفقات المغلقة:** {total}\n✅ **الفوز (TP):** {wins}\n❌ **الخسارة (SL):** {losses}\n🎯 **نسبة النجاح:** {winrate}%\n\n_بناءً على الصفقات التي حددتها بنفسك خلال آخر 30 يومًا._',
        'history_title': '📜 **تاريخ الصفقات:**',
        'no_history': '📭 **لا توجد صفقات بعد!**',
        'vip_text': '💎 **لوحة VIP**\n\n✅ **إشارات خاصة**\n✅ **تحليل متقدم**\n✅ **دعم مخصص**\n\n👤 @RealSurprise',
        'settings_text': '⚙️ **الإعدادات**\n\n🔹 **الإطار الزمني:** {timeframe}\n🔹 **الحالة:** {status}\n🔹 **RR:** 1:{rr}\n🔹 **النمط:** {style}\n🔹 **اللغة:** {lang}',
        'online': 'متصل',
        'offline': 'غير متصل',
        'referral_text': '👥 **نظام الإحالة**\n\nرابط الإحالة الخاص بك:\n`{link}`\n\nلكل 5 إحالات، تحصل على إشارة إضافية واحدة.',
        'support_text': '🆘 **الدعم**\n\n👤 **المعرف:** {support}\n⏰ **وقت الاستجابة:** 24/7',
        'dashboard_btn': '📊 Dashboard',
        'users_btn': '👥 Users',
        'analytics_btn': '📈 Analytics',
        'set_daily_signal_btn': '📊 Set Daily Signal',
        'set_rr_btn': '🎯 Set RR Ratio',
        'set_timeframe_btn': '⏱️ Set Timeframe',
        'referral_bonus_btn': '👥 Referral Bonus',
        'referral_threshold_btn': '🎯 Referral Threshold',
        'reset_signals_btn': '🔄 Reset Signals',
        'bot_lock_btn': '🔒 Bot Lock',
        'signal_control_btn': '🚀 Signal Control',
        'channel_lock_btn': '🔒 Channel Lock',
        'vip_user_btn': '👑 VIP User',
        'delete_user_btn': '🗑️ Delete User',
        'broadcast_btn': '📢 Broadcast',
        'reports_btn': '📊 Reports'
    }
}


def get_text(lang, key):
    """دریافت متن بر اساس زبان"""
    if lang not in LANGUAGES:
        lang = 'fa'
    return LANGUAGES[lang].get(key, key)
